version: '3'

services:
  job-retreiver-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    restart: on-failure
    volumes:
      - .:/go-job-retreiver-docker
      - ${RAW_FILE_PATH}:/go/src/job_posting_retreiver/data
    container_name: go-job-retreiver-docker-app
    environment:
      JB_ENV: ${JB_ENV}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      SENTRY_DSN: ${SENTRY_DSN}
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: on-failure
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data
       