version: '3'

services:
  job-retreiver-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/go-job-retreiver-docker
      - /mnt:/db_volume:rw
    container_name: go-job-retreiver-docker-app
    environment:
      - 'JB_ENV=production'
      - 'DBPath=/db_volume/db_volume/job_aggregator.db'